
// environment.ts (Development environment)
export const environment = {
    production: false,
    coreApiUrl: 'https://amplify-rpm-azurewebservices.betalen.in/api',
    UrlConstants: {
        Authenticate: 'UserAccess/Authenticate',
        VerifyAccesToken: 'UserAccess/VerifyAccesToken',
        GenerateUserCliams: 'UserAccess/GenerateUserCliams',
        Country: 'Country',
        State: 'State',
        City: 'City',
        Status: 'Status',
        Department: 'Department',
        Role: 'Role',
        User: 'Users',
        GetApplicationUser: 'Users/GetUserDetailsByEmail',
        NewsLetter: 'NewsLetter',
        CheckNewsLetter: 'NewsLetter/GetNewsLetterByEmail',
        Product: 'Product/ProductDetails',
        BillingAddress: "BillingAddress",
        GetUserBillingAddress: 'BillingAddress/GetAllBillingAddress',
        ShippmentType: 'ShippmentType',
        ShippingType: 'ShippingType',
        PaymentMethods: 'PaymentMethods',
        Tickets: 'Tickets',
        MyTickets: 'Tickets/GetAllUserTickets',
        PriorityType: 'PriorityTypes',
        Order: 'Order',
        OrdersByUser: 'Order/GetAllOrdersByUser',
        PlaceOrder: 'Order/ProcessOrder',
        HandleOrderPayment: 'Order/HandleOrderPayment',
        HandleOrderProcess: 'Order/HandleOrderProcess',
        fetchCancelledOrders: 'Order/fetchCancelledOrders',
        fetchRejectedOrders: 'Order/fetchRejectedOrders ',
        fetchRefundedOrders: 'Order/fetchRefundedOrders',
        fetchDeleveredOrders: 'Order/fetchDeleveredOrders',
        fetchInTrasitOrders: 'Order/fetchInTrasitOrders',
        fetchUserSpecificOrders: 'Order/fetchUserSpecificOrders',
        PrivacyPolicy: 'PrivacyPolicy',
        RefundAndExchange:'RefundAndExchange',
        Refund:'Refund',
        CancelationPolicy:'CancelationPolicy',
        TermsAndConditions:'TermsAndConditions',
        TermsOfUses:'TermsOfUses',
        fetchUserSpecificPayment:'Payments/fetchUserSpecificPayment'
    },
    Messages: {
        InvalidPassword: "Authentication Failed due to Invalid Password ,Please enter correct password and try again",
        InValidUserName: "Authentication Failed due to Invalid UserName ,Please enter correct username and try again",
        UserWasBlocked: "User Was blocked",
        SomethingwentWrong: "Something went wrong,Please try after sometime"
    },
    Titles: {
        InvalidPassword: "Wrong/Invalid Password",
        InValidUserName: "Worng/Invalid Username",
        UserWasBlocked: "User blocked",
        SomethingWentWrong: "Something Went wrong"
    },
    ErrorCodes: {
        EC1001: 1001,
        EC1002: 1002,
        EC1003: 1003,
        EC1004: 1004
    },
    AppConstants: {
        Roles: {
            DigitalSalesMarketing: "Digital Sales Marketing",
            ProductManager: "Product Manager",
            CustomerServiceRepresentative: "Customer Service Representative",
            Customer: "Customer",
            Developer: "Developer",
            EcommerceManager: "E-commerce Manager",
            WebDeveloper: "Web Developer",
            OperationManager: "Operation Manager",
            GraphicDesigner: "Graphic Designer",
            DataAnalyst: "Data Analyst",
            FashionDesigner: "Fashion Designer",
            Administrator: "Administrator",
            SoftwareEngineer: "Software Engineer",
            User: "User",
            Executive: "Executive",
            Seller: "Seller",
        },
        departments: {
            Sales: "Sales",
        },
        FashionDesignerType: {
            ReadyToWear: "Ready-to-wear",
            EconomyFashion: "Economy fashion",
            HauteCouture: "Haute couture",
            TextileDesigner: "Textile Designer",
            FootwearDesigners: "Footwear designers",
            GraphicDesigner: "Graphic Designer",
            AccessoryDesigner: "Accessory designer",
            AthleticWear: "Athletic wear",
            FastFashion: "Fast fashion",
            MassMarketDesigners: "Mass market designers",
            KidswearDesigners: "Kidswear designers",
            FashionMarketer: "Fashion marketer",
            FashionWriter: "Fashion writer",
            LimitedEdition: "Limited edition",
            Merchandiser: "Merchandiser",
            SpecializedAreasOfFashionDesign: "Specialized areas of fashion design",
            Shirts: "Shirts",
            Jeans: "Jeans",
            Swimwear: "Swimwear",
            Sleepwear: "Sleepwear",
            Sportswear: "Sportswear",
            Jumpsuits: "Jumpsuits",
            Blazers: "Blazers",
            Jackets: "Jackets",
            Shoes: "Shoes",
            MensDresses: "Men's Dresses",
            WomensDresses: "Women's Dresses",
            BabysDresses: "Baby's Dresses",
        },
        Countries: {
            Afghanistan: "Afghanistan",
            Albania: "Albania",
            Algeria: "Algeria",
            Argentina: "Argentina",
            Australia: "Australia",
            Bangladesh: "Bangladesh",
            "USA": "United States of America",
            India: "India",
            Pakistan: "Pakistan",
            "People Republic of China": "People Republic of China",
            Singapore: "Singapore",
            Dubai: "Dubai",
            SaudiArabia: "Saudi Arabia",
            Bangkok: "Bangkok",
        },
        States: {
            TELANGANA: "Telangana",
            ANDHRAPRADESH: "Andhra Pradesh",
            KARNATAKA: "Karnataka",
            MAHARASTRA: "Maharashtra",
            UTTERPRADESH: "Uttar Pradesh",
            MADYAPRADESH: "Madhya Pradesh",
            TAMILNADU: "Tamil Nadu",
            KERALA: "Kerala",
            GOA: "Goa",
            ORISSA: "Odisha",
            PANJAB: "Punjab",
            SINDHU: "Sindh",
            Alabama: "Alabama",
            Alaska: "Alaska",
            Arizona: "Arizona",
            Arkansas: "Arkansas",
            California: "California",
            Colorado: "Colorado",
            Connecticut: "Connecticut",
            HARYANA: "Haryana",
            JAMMUKASHMIR: "Jammu & Kashmir",
            Srinagar: "Srinagar",
        },
        Cities: {
            HYDERABAD: "Hyderabad",
            WARANGAL: "Warangal",
            KARIMNAGAR: "Karimnagar",
            KHAMMAM: "Khammam",
            NIZAMABAD: "Nizamabad",
            MEDAK: "Medak",
            AMARAVATHI: "Amaravathi",
            VISHAKAPATNAM: "Vishakapatnam",
            THIRUPATHI: "Thirupathi",
            VijayaWada: "Vijayawada",
            California: "California",
            Bhadrachalam: "Bhadrachalam",
            Hanmakonda: "Hanmakonda",
            BhadraChalam1: "BhadraChalam1",
            BCM: "BCM",
            Venkatapuram: "Venkatapuram",
            vpm: "vpm",
        },
        Status: {
            "New": "New",
            "Created": "Created"
        },
        Braintree: {
            environment: 'braintree.Environment.Sandbox',
            merchantId: 'q577ct9g9qyq8jt7',
            publicKey: 'bdgysbrrb98f7kb7',
            privateKey: '11568834eefc8a3448a59ac682a34a63',
        }
    }
};
