CREATE TABLE [dbo].[InsurancePolicy]
(
    [InsurancePolicyId]       BIGINT            NOT NULL PRIMARY KEY IDENTITY(1,1),
    [PolicyReference]         VARCHAR(50)       NOT NULL UNIQUE,
    [VIN]                     VARCHAR(20)       NULL,
    [CarRegistrationNo]       VARCHAR(20)       NULL,
    [VehicleClass]            VARCHAR(50)       NULL,
    [VehicleSize]             VARCHAR(20)       NULL,
    [CustomerName]            VARCHAR(100)      NULL,
    [CustomerPhone]           VARCHAR(20)       NULL,
    [CustomerEmail]           VARCHAR(100)      NULL,
    [CustomerLifetimeValue]   DECIMAL(10, 2)    NULL,
    [Gender]                  CHAR(1)           NULL,
    [Education]               VARCHAR(50)       NULL,
    [EmploymentStatus]        VARCHAR(50)       NULL,
    [Income]                  DECIMAL(10, 2)    NULL,
    [MaritalStatus]           VARCHAR(10)       NULL,
    [PolicyType]              VARCHAR(50)       NULL,
    [Policy]                  VARCHAR(50)       NULL,
    [Coverage]                VARCHAR(50)       NULL,
    [EffectiveToDate]         DATETIMEOFFSET    NULL,
    [MonthlyPremiumAuto]      DECIMAL(10, 2)    NULL,
    [MonthsSinceLastClaim]    INT               NULL,
    [MonthsSincePolicyInception] INT            NULL,
    [NumberOfOpenComplaints]  INT               NULL,
    [NumberOfPolicies]        INT               NULL,
    [RenewOfferType]          VARCHAR(50)       NULL,
    [SalesChannel]            VARCHAR(50)       NULL,
    [TotalClaimAmount]        DECIMAL(10, 2)    NULL,
    [State]                   VARCHAR(50)       NULL,
    [LocationCode]            VARCHAR(10)       NULL,
    [Response]                VARCHAR(10)       NULL,
    [CreatedBy]               BIGINT           NULL,
    [CreatedOn]               DATETIMEOFFSET   NULL,
    [ModifiedBy]              BIGINT           NULL,
    [ModifiedOn]              DATETIMEOFFSET   NULL,
    [IsActive]                BIT              NULL
);
